configure: Fix C++11 test with -Werror=missing-declarations
This fixes the following error (copied from config.log):

  conftest.cpp:49:14: error: no previous declaration for 'void
  test_template_alias_sfinae::test()' [-Werror=missing-declarations]

Signed-off-by: Uli Schlachter <psychon@znc.in>
(cherry picked from commit 2d1336dcf3d620f115aec771ddfb86b199a71e21)